//! Implementation of the various GP0 commands.

use super::Psx;

/// Description of the various GP0 commands
pub struct Command {
    /// Callback function to actually perform the command
    pub handler: fn(&mut Psx),
    /// Actual length of the command, in number of FIFO words
    pub len: u8,
    /// This is the amount of overhead bytes accepted on the FIFO when this command is the next to
    /// be executed (see `try_write_command` for more details). These values are taken from
    /// mednafen, I'm not sure how they've been established. I assume it has something to do with
    /// the amount of time taken by these instructions to process?
    pub fifo_len: u8,
    /// Marker for commands that aren't executed with normal PSX timings.
    pub out_of_band: bool,
}

impl Command {
    pub fn len(&self) -> usize {
        self.len as usize
    }

    pub fn fifo_len(&self) -> usize {
        self.fifo_len as usize
    }
}

fn cmd_draw_mode(psx: &mut Psx) {
    let mode = psx.gpu.command_fifo.pop();

    psx.gpu.draw_mode.set(mode);
}

/// Placeholder function
fn cmd_unimplemented(psx: &mut Psx) {
    unimplemented!("GPU command {:08x}", psx.gpu.command_fifo.pop());
}

/// LUT for all GP0 commands (indexed by opcode, bits[31:24] of the first command word)
pub const GP0_COMMANDS: [Command; 0x100] = [
    // 0x00
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x10
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x20
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x30
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x40
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x50
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x60
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x70
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x80
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0x90
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0xa0
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0xb0
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0xc0
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0xd0
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0xe0
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_draw_mode,
        len: 1,
        fifo_len: 2,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    // 0xf0
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
    Command {
        handler: cmd_unimplemented,
        len: 1,
        fifo_len: 1,
        out_of_band: false,
    },
];
